name: Barrel Classic Detect
api: "1.0.0"
main: org.CreadoresProgram.BarrelClassicDetect.Main
version: "1.0.0"
description: "Detects when a ClassiCube player joins your server"
author: Creadores Program
website: "https://github.com/Creadores-Program/Barrel-Classic-Detect"
